ECE297 Storage Server: server.c File Reference
server.c File Reference
This file implements the storage server.
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <string.h>
#include <assert.h>
#include <signal.h>
#include "utils.h"
#include "loghelp.h"
#include <errno.h>
Classes
struct table
A struct a linked list to store the table's configuration paramaters.
struct temp_table_info
A struct to store EACH table's paramters.
struct key
Simply stores the next key in the list and the value (each key is a struct).
struct head
A header for our database.
Defines
#define MAX_SIZE_LENGTH 800
#define MAX_LISTENQUEUELEN 20
The maximum number of queued connections.
Functions
struct table * create_table_bare (char *name_table, struct table_info *temp)
A function that dynamically creates a bare table given its name and table configurations.
struct table * find_table (char *name, struct head *head)
a function to find the table stored inside of our database
struct key * find_key (char *name, struct table *table)
function to find the key stored inside of our database
struct table * create_table (char *name_table, char *name_key, char *value)
struct key * create_key (char *name_key, char *value, struct temp_table_info *temp)
A function that dynamically creates a key given its key name, value.
void insert_table (struct table *new_table, struct head *head)
a function that inserts a table (new_table) inside of our database. Also inserts it into our structs
void insert_key (struct key *new_key, struct table *table)
a function that inserts a key (new_key) inside of our database. Also inserts it into our structs
void delete_table (struct table *target_table, struct table *table)
void delete_key (struct key *target_key, struct table *table)
function that deletes the key from the linked list and sets the next/back value of respective keys in the list
int set_function (char *table_name, char *key_name,char *value, struct head *head, struct temp_table_info *temp)
a function that sets the value of a key based on the value sent. Function is called from handle_command
int get_function (char *table_name, char *key_name, char *value, struct head *head)
a function to get (retreive a value) from our database. Function is called from handle_command
int compare_formats (struct temp_table_info *temp_info, struct table *target_table)
PARSING///.
int query_parser (char *line, struct temp_table_info *temp_info)
a function that parses the query predicates. Function called from handle command
int input_parser (char *line, struct temp_table_info *temp_info)
parses the user's input for a set command and saves it's format in temp_info
int compare_query_format (struct temp_table_info *temp_info, struct table *target_table)
function that compares if the format of the input (for storage_query) matches the columns/types of the table's format
struct key * check_key (struct key *target_key, int index_col, char *operators, char *type, char *value)
a function that checks if the key's value satisfies the condition outlined by the operator
int table_query (struct table *target_table, struct temp_table_info *col_info, struct key *key_array[50])
int handle_command (int sock, char *cmd, FILE **log, struct config_params *params, struct head *head)
Handle command takes in a sentence from the client and performs accordingly.
int main (int argc, char *argv[])
Start the storage server.
int table_query (struct table *target_table, struct temp_table_info *col_info, struct key *key_array[])
takes a set of conditions (col_info) and finds all the keys in the supplied table that match all the conditions
Variables
int didAuthenticate
Detailed Description
This file implements the storage server.
The storage server should be named "server" and should take a single command line argument that refers to the configuration file.
The storage server should be able to communicate with the client library functions declared in storage.h and implemented in storage.c.
At the bottom of the server file, we have implemented all of the functions needed for our database, along with the query function
Definition in file server.c.
Function Documentation
struct key * check_key (struct key * target_key, int index_col, char * operators, char * type, char * value) [read]
a function that checks if the key's value satisfies the condition outlined by the operator
Parameters:
target_key is the key checked
index_col holds the correct index for the key's column/value to match the provided value's type
operators condition to be checked
Returns:
returns the key struct if valid, null if not
Definition at line 1217 of file server.c.
Referenced by table_query().
int compare_formats (struct temp_table_info * temp_info, struct table * target_table)
PARSING///.
function that compares the formats of the user's input with the expected format in the table (used for storage_set)
Parameters:
temp_info contains the format of the columns/types/values of the user input
target_table contains the format of the table, this is compared with the temp provided in temp_info
Returns:
returns -1 for failure, and 0 for success
Definition at line 1008 of file server.c.
Referenced by set_function().
int compare_query_format (struct temp_table_info * temp_info, struct table * target_table)
function that compares if the format of the input (for storage_query) matches the columns/types of the table's format
Parameters:
temp_info a pointer to a struct that contains the format of the input sent
target_table contains the format of the table, this is compared with the temp provided in temp_info
Returns:
returns -1 for failure, and 0 for success
Definition at line 964 of file server.c.
Referenced by handle_command().
struct key * create_key (char * name_key, char * value, struct temp_table_info * temp) [read]
A function that dynamically creates a key given its key name, value.
Parameters:
name_key name of the key
value value to place inside the key
temp struct of the table info
Returns:
struct to the key created
Definition at line 691 of file server.c.
Referenced by set_function().
struct table * create_table_bare (char * name_table, struct table_info * temp) [read]
A function that dynamically creates a bare table given its name and table configurations.
Parameters:
name_table name of the table
table_info information for each table inside the config file
Returns:
struct to the table created
Definition at line 657 of file server.c.
Referenced by main().
void delete_key (struct key * target_key, struct table * table)
function that deletes the key from the linked list and sets the next/back value of respective keys in the list
Parameters:
target_key is the key to be deleted
table is the table the key is contained in
Returns:
nothing
Definition at line 818 of file server.c.
Referenced by set_function().
struct key * find_key (char * name, struct table * table) [read]
function to find the key stored inside of our database
Parameters:
name of the table
head structure of the head to the database
Returns:
struct of the table if found, or null if not found
Definition at line 609 of file server.c.
Referenced by get_function(), and set_function().
struct table * find_table (char * name, struct head * head) [read]
a function to find the table stored inside of our database
Parameters:
name of the table
head structure of the head to the database
Returns:
struct of the table if found, or null if not found
Definition at line 588 of file server.c.
Referenced by get_function(), handle_command(), and set_function().
int get_function (char * table_name, char * key_name, char * value, struct head * head)
a function to get (retreive a value) from our database. Function is called from handle_command
Parameters:
table_name name of the table we must get from
key_name name of the key to retreive from
value returns the value inside
head header to the database
Returns:
0 for success, 1 for key not found, 2 table not found
Definition at line 927 of file server.c.
References find_key(), and find_table().
Referenced by handle_command().
int handle_command (int sock, char * cmd, FILE ** log, struct config_params * params, struct head * head)
Handle command takes in a sentence from the client and performs accordingly.
Parameters:
sock The socket connected to the client.
cmd The command received from the client.
log a pointer to the pointer of the declaration of the file to log
params a pointer to the struct holding the properties inside the config file
head a pointer to the head of our database
Returns:
Returns 0 on success, -1 otherwise.
Definition at line 124 of file server.c.
References compare_query_format(), find_table(), get_function(), input_parser(), logger(), MAX_VALUE_LEN, config_params::password, query_parser(), sendall(), set_function(), table_query(), and config_params::username.
Referenced by main().
int input_parser (char * line, struct temp_table_info * temp_info)
parses the user's input for a set command and saves it's format in temp_info
Parameters:
line to parse
temp_info contains the saved info and format
Returns:
returns -1 for failure, and 0 for success
Definition at line 1155 of file server.c.
Referenced by handle_command().
void insert_key (struct key * new_key, struct table * table)
a function that inserts a key (new_key) inside of our database. Also inserts it into our structs
Parameters:
new_key a struct to the new key
table a struct to the table
Returns:
nothing
Definition at line 750 of file server.c.
Referenced by set_function().
void insert_table (struct table * new_table, struct head * head)
a function that inserts a table (new_table) inside of our database. Also inserts it into our structs
Parameters:
new_table a struct pointing to the table
head a struct pointing to the head of our database
Returns:
nothing
Definition at line 719 of file server.c.
Referenced by main().
int main (int argc, char * argv[])
Start the storage server.
starts the connection and ports
it opens the file to log, processes the time output
creates the tables and keys for the database
processes the config file
calls handle command
Returns:
returns 0 for success, -1 for failure
Definition at line 406 of file server.c.
References create_table_bare(), handle_command(), insert_table(), logger(), MAX_CMD_LEN, MAX_LISTENQUEUELEN, read_config(), recvline(), config_params::server_host, and config_params::server_port.
int query_parser (char * line, struct temp_table_info * temp_info)
a function that parses the query predicates. Function called from handle command
Parameters:
line to parse
temp_info stores the parsed information and format
Returns:
returns -1 for failure, and 0 for success
Definition at line 1053 of file server.c.
Referenced by handle_command().
int set_function (char * table_name, char * key_name, char * value, struct head * head, struct temp_table_info * temp)
a function that sets the value of a key based on the value sent. Function is called from handle_command
Parameters:
table_name name of the table we must set into
key_name name of the key to input
value value to be set
head header to the database (head of table chain)
temp a struct that contains the format of the input, used to check if the format matches the table's format
Returns:
0 for success, 1 for key not found, 2 table not found, 3 unknown, 4 invalid format of input (types do no match columns)
Definition at line 860 of file server.c.
References compare_formats(), create_key(), delete_key(), find_key(), find_table(), insert_key(), and MAX_RECORDS_PER_TABLE.
Referenced by handle_command().
int table_query (struct table * target_table, struct temp_table_info * col_info, struct key * key_array[])
takes a set of conditions (col_info) and finds all the keys in the supplied table that match all the conditions
Parameters:
target_table a struct to the configuartion of that particular table
col_info holds the parsed conditions (from query_parser)
key_array holds the keys that satisfy all the conditions
Returns:
returns -1 for failure, and 0 for success
filled Arr_Keys with the keys that satisfied at least one of the conditions now checking which keys match all conditions
Definition at line 1250 of file server.c.
References check_key().
Referenced by handle_command().