ECE297 Storage Server: storage.c File Reference
storage.c File Reference
This file contains the implementation of the storage server interface as specified in storage.h.
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netdb.h>
#include "storage.h"
#include "utils.h"
#include "loghelp.h"
#include <errno.h>
Functions
int tablecheck (char *string)
receives a string and checks whether it's valid. Standard given according to the M2 document
int keycheck (char *string)
receives a string and checks whether it's valid. Standard given according to the M2 document
int valuecheck (char *string)
receives a string and checks whether it's valid. Standard given according to the M2 document
void * storage_connect (const char *hostname, const int port)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will be conencted with our server
int storage_auth (const char *username, const char *passwd, void *conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will be authenticated with the server
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will have the values found inside the table
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will have set a key along with its values inside the database
int storage_query (const char *table, const char *predicates, char **keys, const int max_keys, void *conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will have all of the keys that pass the operations inside predicates
int storage_disconnect (void *conn)
performs a basic error check and after everything has passed, disconnects from the server
Variables
int didConnect
int didAuthenticate
Detailed Description
This file contains the implementation of the storage server interface as specified in storage.h.
performs all of the sending and receiving with the server, also performs a standard error check on the commands given from client
Definition in file storage.c.
Function Documentation
int keycheck (char * string)
receives a string and checks whether it's valid. Standard given according to the M2 document
Parameters:
string is what we want to make sure is a valid key type
Returns:
return 0 for success, 1 for failure
Definition at line 49 of file storage.c.
Referenced by storage_get(), and storage_set().
int storage_auth (const char * username, const char * passwd, void * conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will be authenticated with the server
Authenticate the client's connection to the server.
Parameters:
username the name of our server we want to join
passwd the password for the server network
conn a pointer to the connection status of the server
Returns:
return 0 for success, -1 for failure
Definition at line 139 of file storage.c.
References generate_encrypted_password(), recvline(), and sendall().
void* storage_connect (const char * hostname, const int port)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will be conencted with our server
Establish a connection to the server.
Parameters:
hostname is the name of the host we want to connect with
port is the port number we want to connect with
return 0 for success, -1 for failure
Definition at line 88 of file storage.c.
References logger().
int storage_disconnect (void * conn)
performs a basic error check and after everything has passed, disconnects from the server
Close the connection to the server.
Parameters:
conn a pointer to the connection status of the server
Returns:
return 0 for success, -1 for failure
Definition at line 368 of file storage.c.
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will have the values found inside the table
Retrieve the value associated with a key in a table.
Parameters:
table name of the table we want to get from
key name of the key
record is the struct holding the configuration parameters of everything inside the configuration file
conn a pointer to the connection status of the server
Returns:
return 0 for success, -1 for failure
Definition at line 176 of file storage.c.
References keycheck(), recvline(), sendall(), tablecheck(), and storage_record::value.
int storage_query (const char * table, const char * predicates, char ** keys, const int max_keys, void * conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will have all of the keys that pass the operations inside predicates
Query the table for records, and retrieve the matching keys.
Parameters:
table name of the table we want to query from
key a member address of the pointer for the string of keys
max_keys is the max number of keys storage query is supposed to return
conn a pointer to the connection status of the server
Returns:
return 0 for success, -1 for failure
Definition at line 302 of file storage.c.
References recvline(), sendall(), and tablecheck().
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
performs a basic error check and after everything has passed, passes the information onto server via sendall after the execution of this function, we will have set a key along with its values inside the database
Store a key/value pair in a table.
Parameters:
table name of the table we want to set to
key name of the key we want to set
record is the struct holding the configuration parameters of everything inside the configuration file
conn a pointer to the connection status of the server
Returns:
return 0 for success, -1 for failure
Definition at line 234 of file storage.c.
References keycheck(), recvline(), sendall(), tablecheck(), and storage_record::value.
int tablecheck (char * string)
receives a string and checks whether it's valid. Standard given according to the M2 document
Parameters:
string,string to perform error check on
Returns:
return 0 for success, 1 for failure
Definition at line 32 of file storage.c.
Referenced by storage_get(), storage_query(), and storage_set().
int valuecheck (char * string)
receives a string and checks whether it's valid. Standard given according to the M2 document
Parameters:
string is what we want to make sure is a valid value type
Returns:
return 0 for success, 1 for failure
Definition at line 66 of file storage.c.