ECE297 Storage Server: utils.c File Reference
utils.c File Reference
This file implements various utility functions that can be used by the storage server and client library.
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <unistd.h>
#include "utils.h"
#include "loghelp.h"
Functions
int sendall (const int sock, const char *buf, const size_t len)
Keep sending the contents of the buffer until complete.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int process_config_line (char *line, struct config_params *params, int *host, int *port, int *user, int *pass)
takes a line passed in from the read configuration function and stores it in the appropriate structs
int read_config (const char *config_file, struct config_params *params)
opens and reads the entire config file, parsing and storing them to structs used in other files
void logger (FILE *file, char *message)
either writes to stdout, a file or does nothing according to the LOGGING constant set in the loghelp.h file
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
Detailed Description
This file implements various utility functions that can be used by the storage server and client library.
Definition in file utils.c.
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters:
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns:
Returns encrypted password.
Definition at line 291 of file utils.c.
References DEFAULT_CRYPT_SALT.
Referenced by storage_auth().
void logger (FILE * file, char * message)
either writes to stdout, a file or does nothing according to the LOGGING constant set in the loghelp.h file
Generates a log message.
Parameters:
file is a pointer to the file created to log to
message is what we want to write to either the file, stdout or
Returns:
nothing
Definition at line 280 of file utils.c.
Referenced by handle_command(), main(), and storage_connect().
int process_config_line (char * line, struct config_params * params, int * host, int * port, int * user, int * pass)
takes a line passed in from the read configuration function and stores it in the appropriate structs
Parameters:
line is each line inside the config file
params is the struct that will hold the entire config file... split into arrays
host is the counter used through each function call -used for error checking
port is the counter used through each function call -used for error checking
user is the counter used through each function call -used for error checking
pass is the counter used through each function call -used for error checking
Returns:
returns 0 for success, -1 for failure
Definition at line 77 of file utils.c.
References MAX_TABLE_LEN, config_params::password, config_params::server_host, config_params::server_port, and config_params::username.
Referenced by read_config().
int read_config (const char * config_file, struct config_params * params)
opens and reads the entire config file, parsing and storing them to structs used in other files
Read and load configuration parameters.
Parameters:
config_file is the name of the config file being parsed
params is a structure that holds everything inside the configuration file
Returns:
returns 0 for success, -1 for failure
Definition at line 234 of file utils.c.
References process_config_line().
Referenced by main().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
In order to avoid reading more than a line from the stream, this function only reads one byte at a time. This is very inefficient, and you are free to optimize it or implement your own function.
Definition at line 39 of file utils.c.
Referenced by main(), storage_auth(), storage_get(), storage_query(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
Keep sending the contents of the buffer until complete.
Returns:
Return 0 on success, -1 otherwise.
The parameters mimic the send() function.
Definition at line 19 of file utils.c.
Referenced by handle_command(), storage_auth(), storage_get(), storage_query(), and storage_set().